#!/usr/bin/env python

"""Exposes classes and functions to perform the lexical analysis of
the models generated by the Boolector SMT solver.
"""

"""See the LICENSE file, located in the root directory of
the source distribution and
at http://verifun.eecs.berkeley.edu/gametime/about/LICENSE,
for details on the GameTime license and authors.
"""


from gametime.smt.parsers.modelLexer import ModelLexer


class BoolectorModelLexer(ModelLexer):
    """Performs the lexical analysis of the models
    generated by the Boolector SMT solver.
    """

    def __init__(self):
        super(BoolectorModelLexer, self).__init__()

    #: List of token names.
    tokens = ModelLexer.tokens + ("LBRACKET", "RBRACKET")

    # Rules for the tokens.
    t_LBRACKET = r"\["
    t_RBRACKET = r"\]"

    def t_NUMBER(self, t):
        r"\d+"
        return t
